### ISSUE TITLE
Increase text section title padding

### ISSUE THREAD

**Issue by willcompanion** [StudioCompanion/companion-studio#150]
This is mainly noticeable on case studies. Need to add more spacing between a paragraph title and the body copy text. Think we just need to increase the padding here. 

![Screenshot 2022-04-29 at 11 24 07](https://user-images.githubusercontent.com/85284662/165927638-7110809f-939b-414f-ae6e-c555ebd71f41.png)

**Comment by joshuaellis** [comment]
@willcompanion can we have a value to implement please?

**Comment by mylespalmer** [comment]
@joshuaellis 8px please.
