### ISSUE TITLE
[bug]: Carousel dots have gone missing

### ISSUE THREAD

**Issue by willcompanion** [StudioCompanion/companion-studio#184]
## 🐛 Bug Report
The dots that sit underneath a media block to indicate how many assets are within a carousel, is no longer there. The padding between the assets indicates that its still there but is maybe hidden. This is for both desktop and mobile. Image captions are still visible.

![Screenshot 2022-05-18 at 17 11 32](https://user-images.githubusercontent.com/85284662/169090914-8ca23b79-39b5-4e91-887f-57574aacfcac.png)

## To Reproduce
I first noticed the problem for the carousel on DO Lectures case study. You can also upload multiple assets into one media block in order to replicate this.

## Expected behavior
The small dots should sit on the far right hand side of the media block for all blocks that have more than one asset uploaded to it. This should be for both desktop and mobile.

## Environment

| Info             | Version(s) |
| ---------------- | ---------- |
| Browser          |       Chrome     |
| Device           |   Desktop       |
| Operating System |     MacOS Monterey       |

**Comment by elenamarinaki** [comment]
@willcompanion @joshuaellis 

sorry, I do not see this in the figma file - is this where these dots are supposed to be? I also added a temporary caption, this will be removed.

<img width="892" alt="Screen Shot 2022-05-19 at 11 30 44" src="https://user-images.githubusercontent.com/76445935/169273825-133c73e1-3ec8-4a11-a22f-47f476df94e7.png">

**Comment by joshuaellis** [comment]
yep looks like it 
<img width="909" alt="image" src="https://user-images.githubusercontent.com/37798644/169276765-a15153de-a4c3-4fca-8e09-2ca138874dd0.png">
