### ISSUE TITLE
[request]: Inline text links need a new state

### ISSUE THREAD

**Issue by willcompanion** [StudioCompanion/companion-studio#186]
## 🚀 Feature Proposal
Currently inline text links only show an underline on hover. This makes it hard to realise what is and isnt a link and impossible to see on mobile. 

Perhaps the link should remain constantly underlined and we introduce a new state on hover? Perhaps a 50% opactiy.

See below for current functionality vs proposed.

**Current.**

https://user-images.githubusercontent.com/85284662/169243566-ed1a6608-773b-47d7-9dfa-a4396c2f1282.mov

**Proposed**

https://user-images.githubusercontent.com/85284662/169243614-8b409147-bb99-4491-815c-ad8397406ab5.mov

**Comment by joshuaellis** [comment]
I actually think this was built incorrectly where instead the underline should always be there & on hover it disappears.

**Comment by willcompanion** [comment]
Thats works too!

**Comment by elenamarinaki** [comment]
@joshuaellis @willcompanion 

just making sure - the desired effect is: 
1. the underline is always there
2. it disappears on hover, while there's no change in colour or opacity

is this correct?

**Comment by joshuaellis** [comment]
yep!

**Comment by willcompanion** [comment]
Yes thats correct! thank you
