### ISSUE TITLE
Flash of Unstyled Content (FOUC)

### ISSUE THREAD

**Issue by mylespalmer** [StudioCompanion/companion-studio#189]
[![Screenshot_2022-05-19_10-53-00.png](https://mrkr.io/s/6286218c94e705a441cda6a1/2)](https://mrkr.io/s/6286218c94e705a441cda6a1/0)

*Steps to reproduce:*

Hard refresh the site (CMD SHIFT R) or open it in a new tab for the first time.

*Actual result:*

- You always see the deep blue
- You can see the unstyled content underneath it
- It happens everytime without fail

Expected result:

- We should not see any unstyled content when the page loads. Images loading in is fine, but we shouldn't be seeing unstyled text, hidden elements or anything else.
- I would expect it to match DO + Cellular in this regard.

---

**Source URL:** [https://companion-studio-eta.vercel.app/](https://companion-studio-eta.vercel.app/)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/6286218c94e705a441cda6a4_c28afe7637890655)

<table><tr><td><strong>Browser</strong></td><td>Chrome 101.0.4951.64</td></tr><tr><td><strong>Screen Size</strong></td><td>1728 x 1117</td></tr><tr><td><strong>OS</strong></td><td>OS X 12.0.1</td></tr><tr><td><strong>Viewport Size</strong></td><td>1441 x 968</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;2x</td></tr></table>

**Comment by joshuaellis** [comment]
Caused by upgrading react to version 18 (lol great)
