### ISSUE TITLE
Custom BG Colour Per Page Card

### ISSUE THREAD

**Issue by mylespalmer** [StudioCompanion/companion-studio#192]
[![Screenshot_2022-05-19_11-12-20.png](https://mrkr.io/s/6286261473de3cf713478059/2)](https://mrkr.io/s/6286261473de3cf713478059/0)

Steps to reproduce:
Hover over the page card on the homepage

Actual result:
If it's set to dark theme because you want dark text, it then has the white BG on hover, but that causes it to lose it's frame.

Expected result:
Can we just set a custom hex colour per page card, which is then what is shown in the BG?

'Theme' can be kept for type colours, though.

---

**Source URL:** [https://companion-studio-eta.vercel.app/](https://companion-studio-eta.vercel.app/)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/6286261473de3cf71347805c_974c24b3da237152)

<table><tr><td><strong>Browser</strong></td><td>Chrome 101.0.4951.64</td></tr><tr><td><strong>Screen Size</strong></td><td>1728 x 1117</td></tr><tr><td><strong>OS</strong></td><td>OS X 12.0.1</td></tr><tr><td><strong>Viewport Size</strong></td><td>1359 x 968</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;2x</td></tr></table>

**Comment by elenamarinaki** [comment]
@joshuaellis @mylespalmer 

Could you please elaborate a bit more on this one? What we have now is:
- every card has a theme that is being passed from `Sanity` as info 
- according to this, the letters are a shade of white while the background becomes a shade of black on hover and vice versa.

1. Where are we going to be applying this custom background? Is this referring to the background colour on hover?
2. Are we going to be passing this one through cms I assume?

**Comment by joshuaellis** [comment]
1. the background of `CardWrapper` inside `CardHome`
2. yes it needs to be a string that takes a hex value
