### ISSUE TITLE
Team Images Aspects

### ISSUE THREAD

**Issue by mylespalmer** [StudioCompanion/companion-studio#204]
[![Screenshot_2022-05-20_10-34-04.png](https://mrkr.io/s/62876e9cbe35e70a9062afb0/2)](https://mrkr.io/s/62876e9cbe35e70a9062afb0/0)

Steps to reproduce:

Visit the team page

Actual result:

See screenshot. 

Expected result:
Team images should all be forced into the same aspect ratio and fill the space, the image can just be centered within that.

Please see Figma: https://www.figma.com/file/2ElkrEYuUaje7CV7HDdxyj/The-Actual-Truth?node-id=1%3A808

---

**Source URL:** [https://companion-studio-eta.vercel.app/team](https://companion-studio-eta.vercel.app/team)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/62876e9cbe35e70a9062afb3_34a283e6f4435214)

<table><tr><td><strong>Browser</strong></td><td>Chrome 101.0.4951.64</td></tr><tr><td><strong>Screen Size</strong></td><td>1728 x 1117</td></tr><tr><td><strong>OS</strong></td><td>OS X 12.0.1</td></tr><tr><td><strong>Viewport Size</strong></td><td>1360 x 968</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;2x</td></tr></table>

**Comment by joshuaellis** [comment]
Where would this initial aspect ratio come from? The other issue i forsee is previously we werent enforcing aspect ratios they come from the CMS with the image and this goes against that.

**Comment by mylespalmer** [comment]
It's a 16:9 aspect ratio.

I can export them all as 16:9 and then force it, that's fine if it fixes it — I don't know where the images have been used from (if it's from Dropbox, those are not prepared assets).

**Comment by joshuaellis** [comment]
I think it makes more sense to upload the images at their desired ratio. I'm not sure where the images came from in the first place.

**Comment by mylespalmer** [comment]
Got it, closing.
