### ISSUE TITLE
Team value images

### ISSUE THREAD

**Issue by mylespalmer** [StudioCompanion/companion-studio#205]
[![Screenshot_2022-05-20_10-36-20.png](https://mrkr.io/s/62876f2400265b9ce5697877/2)](https://mrkr.io/s/62876f2400265b9ce5697877/0)

Steps to reproduce:

Visit the team page

Actual result:

All images are different sizes, scales, quality.

Expected result:

All of the images have the same height and this changes on breakpoints (it's 125px for desktop and 85px for mobile, may need bigger for like a 1440+ breakpoint). 

They will then align perfectly as a grid, and have consistent gaps and sizing.

Please see the Figma here: 
https://www.figma.com/file/2ElkrEYuUaje7CV7HDdxyj/The-Actual-Truth?node-id=1%3A808

---

**Source URL:** [https://companion-studio-eta.vercel.app/team](https://companion-studio-eta.vercel.app/team)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/62876f2400265b9ce569787a_d714e3b639bc8467)

<table><tr><td><strong>Browser</strong></td><td>Chrome 101.0.4951.64</td></tr><tr><td><strong>Screen Size</strong></td><td>1728 x 1117</td></tr><tr><td><strong>OS</strong></td><td>OS X 12.0.1</td></tr><tr><td><strong>Viewport Size</strong></td><td>1360 x 968</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;2x</td></tr></table>

**Comment by mylespalmer** [comment]
@joshuaellis, is this the same issue as #204?

**Comment by joshuaellis** [comment]
In a way yes, we should be attempting to upload images at their required aspect ratios. This causes some issues in situations like this where each image would have a large bounding box. 

Would it work for you if the images were exported with said bounding box?

**Comment by mylespalmer** [comment]
I think it should be OK — just pondering if it would make a difference when breakpoints change, but theoretically as long as it stays the same AR it should be fine.

I'll make and test.
