### ISSUE TITLE
Low-res assets on Approach

### ISSUE THREAD

**Issue by mylespalmer** [StudioCompanion/companion-studio#207]
[![Screenshot_2022-05-20_10-41-54.png](https://mrkr.io/s/6287707294e705a441d0585b/2)](https://mrkr.io/s/6287707294e705a441d0585b/0)

Steps to reproduce:

Visit the approach page at a browser width of about 1400px.

Actual result:

The images seem to be served at a very low quality and not at 2x size. It's saying the rendered size is 663 × 708 px.

Is this in the source image or the code that is the issue?

Expected result:

Images should be sharp and crisp. Even when opening the original source, it's very muddy: https://cdn.sanity.io/images/jdgiqwyc/staging/f1ecbb491f0516d7c94282f367d0ad08c8cd035f-657x702.webp?w=2048&q=75&auto=format

---

**Source URL:** [https://companion-studio-eta.vercel.app/approach](https://companion-studio-eta.vercel.app/approach)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/6287707294e705a441d0585e_5568b350695fa572)

<table><tr><td><strong>Browser</strong></td><td>Chrome 101.0.4951.64</td></tr><tr><td><strong>Screen Size</strong></td><td>1728 x 1117</td></tr><tr><td><strong>OS</strong></td><td>OS X 12.0.1</td></tr><tr><td><strong>Viewport Size</strong></td><td>1360 x 968</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;2x</td></tr></table>

**Comment by joshuaellis** [comment]
I would suspect this to be the asset uploaded cc @willcompanion

**Comment by mylespalmer** [comment]
Just checked and downloaded from CMS — seems it's happened in a webp conversion somewhere. First asset for example is a PNG, right size, crisp. Asset 05 is a dud.

@joshuaellis are we converting to `webp` in the CMS, or uploading as `webp` first?

<img width="525" alt="CleanShot 2022-05-20 at 11 56 46@2x" src="https://user-images.githubusercontent.com/12728291/169513948-2407f64e-40e3-466e-982a-3f13be7e94cd.png">

**Comment by joshuaellis** [comment]
When the asset is requested the CMS delivers a recommended file type. We'd have to look into why the image is not as crisp as we'd expect

**Comment by mylespalmer** [comment]
Sorry, I got into calls, but I have assets to use here to replace for testing!

**Comment by mylespalmer** [comment]
I have replaced those and they now seem sharp — ty!
