### ISSUE TITLE
Images shouldn't crop on approach

### ISSUE THREAD

**Issue by mylespalmer** [StudioCompanion/companion-studio#210]
[![Screenshot_2022-05-21_10-26-45.png](https://mrkr.io/s/6288be657edd4dd0f403ad21/2)](https://mrkr.io/s/6288be657edd4dd0f403ad21/0)

Steps to reproduce:

Resize the browser on the approach page

Actual result:

The images crop into each other, I presume because the text is long and therefore it is matching the height and then cropping in.

All of these images are the same aspect ratio, and could be PNGs, and therefore be fit instead — would that help?

Alternatively, do we introduce an in-between breakpoint to help typography (i.e size it down but keep the horizontal layout) before mobile?

---

**Source URL:** [https://companion-studio-eta.vercel.app/approach](https://companion-studio-eta.vercel.app/approach)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/6288be657edd4dd0f403ad24_95038c8047143d90)

<table><tr><td><strong>Browser</strong></td><td>Chrome 101.0.4951.64</td></tr><tr><td><strong>Screen Size</strong></td><td>1728 x 1117</td></tr><tr><td><strong>OS</strong></td><td>OS X 12.0.1</td></tr><tr><td><strong>Viewport Size</strong></td><td>821 x 968</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;2x</td></tr></table>

**Comment by joshuaellis** [comment]
I find what you're suggesting a little unclear. How do you want to approach this? @willcompanion noticed it too.

We could just not have the image stretch to height so there would be whitespace on the left instead of the right in these circumstances.
