### ISSUE TITLE
Image Offset on Homepage

### ISSUE THREAD

**Issue by mylespalmer** [StudioCompanion/companion-studio#214]
[![Screenshot_2022-05-22_12-46-52.png](https://mrkr.io/s/628a30bcb332d8289e281c2e/2)](https://mrkr.io/s/628a30bcb332d8289e281c2e/0)

Steps to reproduce:

A bit of an odd one that might require a huddle, but essentially, I have created an asset that has an image (the globe) inside — this globe is set towards the top of the image, because if it is centered, it goes underneath the title.

However, when doing this, it looks good at smaller browser widths but when sizing upwards, more space is added and it then seems to be totally off center.

When resizing width, I know we're using padding-top % to manage the ratio etc, but is there a reliable way I can create something that has an offset in the source and then always remains centered?

Hover the approach image to see what I mean.

---

**Source URL:** [https://companion-studio-eta.vercel.app/](https://companion-studio-eta.vercel.app/)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/628a30bcb332d8289e281c31_45cdf77a28d714cc)

<table><tr><td><strong>Browser</strong></td><td>Chrome 101.0.4951.64</td></tr><tr><td><strong>Screen Size</strong></td><td>1728 x 1117</td></tr><tr><td><strong>OS</strong></td><td>OS X 12.0.1</td></tr><tr><td><strong>Viewport Size</strong></td><td>1396 x 1000</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;2x</td></tr></table>

**Comment by joshuaellis** [comment]
To have the consistent offset you would need to move it by only X pixels as opposed to a percentage (which is what is happening now) this would create a very specific edge case for a particular card thus creating what I believe to be an unnecessary complexity for the Cards... It also then adds complexity to animating the assets up slightly.

So we can do it by adding a value if you really want, but my advise is not to implement such a feature for one edge case.

**Comment by mylespalmer** [comment]
piss.
