### ISSUE TITLE
[request]: Arrow, Pause, Play & Dots

### ISSUE THREAD

**Issue by mylespalmer** [StudioCompanion/companion-studio#218]
## 🚀 Feature Proposal

Currently I find the dots, the arrow, the pause and play quite hard to know that they are there — often just getting lost and not really standing off, meaning I don't engage with them — particularly the carousel.

What alt's can we try?

**Comment by willcompanion** [comment]
@mylespalmer, @joshuaellis a couple of options below

**Option 1**

The controls have a constant fixed position with the same styling we use for the mobile controls (within a white button). Video controls would sit in the bottom right like the currently do for mobile and carousel arrows would sit horizontally central for both the left and right arrows. We could also change the carousel dots to a larger font and use '1 of X'.

![Carousel 1](https://user-images.githubusercontent.com/85284662/169770131-0e209223-7235-4ecd-8f9a-fa2953352f6b.jpg)

**Option 2**

The controls would follow the users mouse like it currently does, but we use the mobile styling for the buttons and making them stand out more across the artwork. This would obviously only be for desktop and mobile would stay the same as it currently is.

![Carousel 2](https://user-images.githubusercontent.com/85284662/169770402-e043ba6e-650f-4f1f-b4ee-a4b449feac1b.jpg)

I think my personal preference would be the second option but let me know your thoughts

**Comment by mylespalmer** [comment]
Option 2 + instead of 1 of 3, can we see bigger dots please?

**Comment by mylespalmer** [comment]
Changed my mind, keep the dots as they are and do **Option 2** for now — I think _with autoplaying_ this will work.
