### ISSUE TITLE
Double image present on /team

### ISSUE THREAD

**Issue by mylespalmer** [StudioCompanion/companion-studio#223]
[![Screenshot_2022-05-22_21-17-24.png](https://mrkr.io/s/628aa86473de3cf7134f415a/2)](https://mrkr.io/s/628aa86473de3cf7134f415a/0)

This is irritating.

Do we either change the difference value, or, do we not include that message us block on every page?

---

**Source URL:** [https://companion-studio-eta.vercel.app/team](https://companion-studio-eta.vercel.app/team)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/628aa86473de3cf7134f415d_6fac213419f8d58f)

<table><tr><td><strong>Browser</strong></td><td>Chrome 101.0.4951.64</td></tr><tr><td><strong>Screen Size</strong></td><td>1728 x 1117</td></tr><tr><td><strong>OS</strong></td><td>OS X 12.0.1</td></tr><tr><td><strong>Viewport Size</strong></td><td>1728 x 1000</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;2x</td></tr></table>

**Comment by willcompanion** [comment]
@mylespalmer i think its quite important to keep the message banner on every page, so ive mocked up a few different alternative illustrations that could go there instead.

**Option 1**

![Team 1](https://user-images.githubusercontent.com/85284662/169772952-10dd5d37-9cbe-43c6-80bb-e6c4a8ba8d20.jpg)

**Option 2**

![Team 2](https://user-images.githubusercontent.com/85284662/169773003-dcdc8ca0-c99a-400e-a8c9-d325b0fd201e.jpg)

**Option 3**

![Team 3](https://user-images.githubusercontent.com/85284662/169773042-a696a1d4-68fb-4e9b-b628-e81f33ed5da5.jpg)

**Comment by mylespalmer** [comment]
Is it too much to use the below, considering the one without background is used for 'approach' on home?

![pt_globe_with_background_approach](https://user-images.githubusercontent.com/12728291/169783374-de88586d-77da-4ea0-8307-987aa548db2f.gif)

**Comment by mylespalmer** [comment]
Seems he will need centering up in code (as it looks as if there's a margin on the bottom that's odd or something isn't calculating right) — but then I am good with bird, turtle or ship.

Wish it could be dog, but don't have him isolated.

Although @joshuaellis if we could serve a random asset from a pool on each page visit, I would probably ask Pat to isolate dog + fox too.

<img width="1728" alt="CleanShot 2022-05-23 at 22 00 42@2x" src="https://user-images.githubusercontent.com/12728291/169905479-be463ab1-f086-4835-99e9-11b4007b3936.png">
