### ISSUE TITLE
Homepage Limna Asset

### ISSUE THREAD

**Issue by mylespalmer** [StudioCompanion/companion-studio#224]
[![Screenshot_2022-05-22_21-18-11.png](https://mrkr.io/s/628aa893416b11207ab7f32d/2)](https://mrkr.io/s/628aa893416b11207ab7f32d/0)

I think that this needs to be an animated version of the app on the background, rather than a static.

Do we have any screen recordings currently of Limna, that aren't theoreticals like Jacks animations?

---

**Source URL:** [https://companion-studio-eta.vercel.app/](https://companion-studio-eta.vercel.app/)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/628aa893416b11207ab7f330_85bfe142020aa1de)

<table><tr><td><strong>Browser</strong></td><td>Chrome 101.0.4951.64</td></tr><tr><td><strong>Screen Size</strong></td><td>1728 x 1117</td></tr><tr><td><strong>OS</strong></td><td>OS X 12.0.1</td></tr><tr><td><strong>Viewport Size</strong></td><td>1728 x 1000</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;2x</td></tr></table>

**Comment by willcompanion** [comment]
@mylespalmer not currently but I can create one easily enough. Leave it with me 👍
