### ISSUE TITLE
Privacy Typography Requires TLC

### ISSUE THREAD

**Issue by mylespalmer** [StudioCompanion/companion-studio#242]
[![Screenshot_2022-05-24_09-17-42.png](https://mrkr.io/s/628ca2b680c608de7a5e1ef3/2)](https://mrkr.io/s/628ca2b680c608de7a5e1ef3/0)

Just need to swap about type styles.

---

**Source URL:** [https://companion-studio-eta.vercel.app/privacy](https://companion-studio-eta.vercel.app/privacy)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/628ca2b680c608de7a5e1ef6_183f32f0c519bd92)

<table><tr><td><strong>Browser</strong></td><td>Chrome 101.0.4951.64</td></tr><tr><td><strong>Screen Size</strong></td><td>2560 x 1440</td></tr><tr><td><strong>OS</strong></td><td>OS X 12.0.1</td></tr><tr><td><strong>Viewport Size</strong></td><td>1385 x 1000</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;2x</td></tr></table>

**Comment by mylespalmer** [comment]
OK, I have TLC'd that page in the CMS, but spacing and things is a bit all over the place — as I can't tell soft returns vs hard returns and the gaps between headings is a bit 🤮.

Might need some dev TLC to work out where `<br>` and things is being inserted vs not. I did try doing double returns and stuff like that to get desired spacing but no luck.

**Comment by joshuaellis** [comment]
You caught a few styling edge cases we hadn't considered so i've amended those, lets discuss more progress in the PR though.
