### ISSUE TITLE
[request]: Use anything else but a GIF

### ISSUE THREAD

**Issue by joshuaellis** [StudioCompanion/companion-studio#244]
## 🚀 Feature Proposal

This image is way to big (3MB):

https://cdn.sanity.io/images/jdgiqwyc/staging/b91cbac4e64f803234a343e63214bb8fed3b59d9-1939x1500.gif?w=64&blur=50&q=30&auto=format

And thus harms our Lighthouse Score, lets change it to a webp or a video idm.

**Comment by mylespalmer** [comment]
@joshuaellis I believe this is done, mind verifying?
