### ISSUE TITLE
HLS Loading Icon

### ISSUE THREAD

**Issue by mylespalmer** [StudioCompanion/companion-studio#247]
[![Screenshot_2022-05-26_17-55-53.png](https://mrkr.io/s/628fbf29f92e8285050a0f1c/2)](https://mrkr.io/s/628fbf29f92e8285050a0f1c/0)

Steps to reproduce:

I think that I understand we are using Mux for adaptive streaming, ie it will serve the video At a quality it can play back and then up the res when it gets the bandwidth. 

Is it possible to show an icon or state when the video isn’t at its highest res, which can inform the user that it’s still technically loading?

Have done this on projects w Mux in the past but not in Companion times

---

**Reported by:** Myles Palmer (myles@mylespalmer.co.uk) - [Contact via Marker.io](https://app.marker.io/i/628fbf29f92e8285050a0f1f_805e67a2ff93e06d?comments=1)

**Source URL:** [https://companion-studio-eta.vercel.app/projects/limna](https://companion-studio-eta.vercel.app/projects/limna)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/628fbf29f92e8285050a0f1f_805e67a2ff93e06d)

<table><tr><td><strong>Browser</strong></td><td>Safari 15.4</td></tr><tr><td><strong>Screen Size</strong></td><td>390 x 844</td></tr><tr><td><strong>OS</strong></td><td>iOS 15.4.1</td></tr><tr><td><strong>Viewport Size</strong></td><td>390 x 781</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;3x</td></tr></table>

**Comment by joshuaellis** [comment]
@willcompanion would you be able to supply a design for this?

**Comment by mylespalmer** [comment]
Could we have this please:

https://codepen.io/mylespalmer/pen/MWQGJqy

Can it match the size of the play/pause button and be anchored to the top right of the asset.
