### ISSUE TITLE
Get rid of team carousel until we have img?

### ISSUE THREAD

**Issue by mylespalmer** [StudioCompanion/companion-studio#249]
[![Screenshot_2022-05-26_18-35-07.png](https://mrkr.io/s/628fc85bd5b3550662990109/2)](https://mrkr.io/s/628fc85bd5b3550662990109/0)

Maybe we just nuke the top auto marquee scroller until we have enough images and in the meantime start with the team area? 

@willcompanion

---

**Reported by:** Myles (myles@mylespalmer.co.uk) - [Contact via Marker.io](https://app.marker.io/i/628fc85bd5b355066299010c_15223abdb6176dd9?comments=1)

**Source URL:** [https://companion-studio-eta.vercel.app/team](https://companion-studio-eta.vercel.app/team)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/628fc85bd5b355066299010c_15223abdb6176dd9)

<table><tr><td><strong>Browser</strong></td><td>Safari 15.4</td></tr><tr><td><strong>Screen Size</strong></td><td>390 x 844</td></tr><tr><td><strong>OS</strong></td><td>iOS 15.4.1</td></tr><tr><td><strong>Viewport Size</strong></td><td>390 x 667</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;3x</td></tr></table>

**Comment by mylespalmer** [comment]
@joshuaellis — is it possible to check if the field is empty in the CMS and then if it is hide the block?

I have removed images.

**Comment by joshuaellis** [comment]
yes this has been actioned.
