### ISSUE TITLE
[request]: As a user I want to be able to view open positions from the team page

### ISSUE THREAD

**Issue by willcompanion** [StudioCompanion/companion-studio#261]
## 🚀 Feature Proposal

Can we add in a button to link to our jobs board (homerun?) page underneath the qualities section in the team page?

This button should:
• Be styled the same as our dark CTA style. eg: "Message us"
• Open in a new tab
• Be able to be turned on and off when we have open positions

**Comment by joshuaellis** [comment]
This was previously removed by @mylespalmer in the last design iteration. Have you both discussed this?

**Comment by willcompanion** [comment]
ah okay. No we havent discussed it. Will wait for @mylespalmer to chime in here

**Comment by mylespalmer** [comment]
Is it possible to just have an optional button under the heading? I know that the heading currently reads with a `:`, but we can rewrite that?

**Comment by joshuaellis** [comment]
@willcompanion if you can design it & put it on this thread, it can be reviewed then implemented 👍🏼

**Comment by willcompanion** [comment]
<img width="1503" alt="Screenshot 2022-06-07 at 16 47 40" src="https://user-images.githubusercontent.com/85284662/172424532-654ece02-34d8-4b7e-bc17-249d7579fa28.png">
<img width="413" alt="Screenshot 2022-06-07 at 16 47 52" src="https://user-images.githubusercontent.com/85284662/172424561-24912d46-9a7d-4e7c-8df8-7405210af40d.png">

**Comment by mylespalmer** [comment]
Yup
