### ISSUE TITLE
Carousel dots showing on non carousel

### ISSUE THREAD

**Issue by mylespalmer** [StudioCompanion/companion-studio#274]
[![Screenshot_2022-06-07_13-47-48.png](https://mrkr.io/s/629f57044e4e9b11c984b54c/2)](https://mrkr.io/s/629f57044e4e9b11c984b54c/0)

Visit the Limna case study — for some odd reason the dots are there — only on the mobile and 'tablet' view, but inside the container.

---

**Source URL:** [https://companion-studio-eta.vercel.app/projects/limna](https://companion-studio-eta.vercel.app/projects/limna)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/629f57044e4e9b11c984b54f_2fa7774bb1ef1f09)

<table><tr><td><strong>Browser</strong></td><td>Chrome 102.0.5005.61</td></tr><tr><td><strong>Screen Size</strong></td><td>1728 x 1117</td></tr><tr><td><strong>OS</strong></td><td>OS X 12.0.1</td></tr><tr><td><strong>Viewport Size</strong></td><td>826 x 1000</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;2x</td></tr></table>

**Comment by joshuaellis** [comment]
thats in the asset.
