### ISSUE TITLE
[request]: Homepage Typography

### ISSUE THREAD

**Issue by mylespalmer** [StudioCompanion/companion-studio#276]
## 🚀 Feature Proposal

- [x] Change typesize to XXL on desktop
- [x] Increase max width to 87% from 75% on desktop
- [x] Swap the homepage layout to mobile from 1200px downwards

<img width="1768" alt="CleanShot 2022-06-08 at 09 23 38@2x" src="https://user-images.githubusercontent.com/12728291/172569685-67aad2e5-f717-4303-8124-ac20258b0463.png">

**Comment by joshuaellis** [comment]
This is controlled by the richtext renderer so you if you want these changes you'll have to loose the richtext capabilities. Are you okay with that @mylespalmer?

**Comment by mylespalmer** [comment]
https://www.youtube.com/watch?v=klGWvRsLQKU
