### ISSUE TITLE
Caption font size too large 

### ISSUE THREAD

**Issue by mylespalmer** [StudioCompanion/companion-studio#278]
[![Screenshot_2022-06-11_19-52-40.png](https://mrkr.io/s/62a4f2886aea27ab0bd14bdc/2)](https://mrkr.io/s/62a4f2886aea27ab0bd14bdc/0)

The caption font size should be XS (12), rather than S (17) — it is set as 'small copy' in Sanity — perhaps there isn't a setting for XS and this is why, as it seems there's nothing smaller than 'small copy'.

---

**Source URL:** [https://companion-studio-eta.vercel.app/projects/vanmoof](https://companion-studio-eta.vercel.app/projects/vanmoof)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/62a4f2886aea27ab0bd14bdf_280d9e719546ab1b)

<table><tr><td><strong>Browser</strong></td><td>Chrome 102.0.5005.115</td></tr><tr><td><strong>Screen Size</strong></td><td>1728 x 1117</td></tr><tr><td><strong>OS</strong></td><td>OS X 12.0.1</td></tr><tr><td><strong>Viewport Size</strong></td><td>1373 x 1000</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;2x</td></tr></table>

**Comment by joshuaellis** [comment]
In the carousel revision work @willcompanion did it's `S`. So do you want this changing to `XS` still @mylespalmer?

**Comment by mylespalmer** [comment]
Ah, yes please @joshuaellis

**Comment by joshuaellis** [comment]
this has been deployed to the CMS so you can use XS typesizes.
